name: Flutter Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'functions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'
          channel: 'stable'
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Flutter Install
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Flutter Test
        run: flutter test --platform chrome
      - name: Flutter Build
        run: flutter build web --release --web-renderer html
