name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Build
        run: flutter build web --release --web-renderer html
      - name: setup Firebase
        run: npm install -g firebase-tools
      - name: deploy to Firebase Hosting
        run: firebase deploy --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
